sudo: required
dist: trusty
language: node_js
node_js:
- 8
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_script:
- npm run build
env:
  global:
  - secure: TZcRaNm0W1KaJgid6yiXa+Zfghk/v2rjqZDUoLfoSA78I4i8Vk7/g55VSa4SofqUiqPM54DRNRxgsEHyv0/I6SMEa304Ts9gDFLW5C8IOfhPsq8OCdfkH73tio+itU8Vd2krbjj0NQ+Vi1c9pq4Bfy4Gps8X+nhbpjHgtcilBseDN12Fmz7llETcRE985NpTum4WWDvA1PaSR9NySPKGxrlsMCT3kubnk7vsi3fxQqRfAIFPtXGmY4177LHC5ofpgqkjWmQOm3WkG/nRCq3lDITktwVWUqd3NdIcTLnPiU8Ip4HljIGxzZPGx8BjyMBWOt/JR0vabi9lJXmisxrggLixGr5q8iHYMD/yBFcDTb+L1VvZjsqjNs9wxBcT0DcG52hNTcweqhSjp69I11FY/x1Evw+E5Dtky0lBN0qNz8L48J8j5OL/fJj8d6uW+6TE6/2SPrMQREZymBIf35Auux+PibG+1HFuHitzHYKgjQ5i0c5Mvx78gaGvrA3rqp0DWLWqwjvqgEFUvZlZjR/F+LKpdd+9GFu2jZ66rEqi+uZamj0sDBs90q7Af5mYk94Xq7U5FWeLcfJdU1ln2hXgk1wUqPxXAdRW9Bd+i2M4zET31v6aHGj+CZTf+GNcWTOdDbCtvN29qM/L9M5V0/9bcDcWulcWPFgB/vo30Q0EBL4=
  - secure: GpCGBhjnOYOx12giMw98CBqcbbZCo3tRUnxoRtxOcO5fzq6zWDcuwlhB8T8Wm8BInpkphnK62EJ96R1xNIvkSDh3warrpY03Hmc2dtyGNb2OSu9zyfK8njuzFiCevzeX6AktyePWP8dKbfUOVDiCljwC9sJqxpcc+AUPbaGzbbQgZQusbJDGZKAWiUrmqecHdndih2P6lrjmWmrz43PO0h66NOVFvuJmGFtIFHYUxltEJMRXkpwg1/Z8Z4bXtkNvt9ucQ1Q8nK6sM2lz5nVMFjZgqPXgT7EhKWEnBl5K+z+q+iychZfZ+hAe0A7JAhPbP5DoxiNyn+/bI/E+FpAtEw/1fKwv53KFjresGUaL0E+WBsPTAYKSO/vZ2Ms1Ke5ROPizjR6j8KZXVD9SCdRH0xqIDFu/4w+PJyU2wURFbHrMUMQSq/egUH31rWHiX4EpEZFbqrqLPLU7vBYK1gdz4Jszoh2qoDu2LnpMhX3GRDg0D3/mFa2ov50vCmS/nTq33kzTbO+kHPpyULDxUHs1ZkkEfMpJ08fIwzFc+Nz6MVQCaguw7ylERAAr86xfBQg/A1z2NAOdggQajzXQ9rBLqgiQbtxcxlGQNVFRqt8bi0t3sRgx42wygI0vzwngA5VI+1WqSBuGKIAGWnl/59g0BoCfEND58OEGzte8XKa+IbI=
  - CONSOLE_CONFIG_S3_BUCKET=resourcesco-console-config
  - CONSOLE_DATA_S3_BUCKET=resourcesco-console-data
  - secure: c9ZtBAl7JdP4PwdozKWrMy0XTtdMRIhJ5TPi3I6T6k6nLzbidIt9mgBR5r9vWbLiSnuoESJBU51jJkGyA2XpCh/6J6M1D3KeS4Kj/U7RWG32AiOjJAmqfzTbfR32fy3WYXHiWeVyl7AG70OpeB1cop4IgD1He1PzBnQRSHSSOiRF93I9X1pZHXQ1nB8wGe8yd8O+UVshMKu9+D5bkW3UmiztC7WfaJEt/trDCscpZNxmLEb9YdMjfUCwIngl73P4jFs/LqoKUnH7jVoEBymbsDzu79swx5cU/5j2/hjTNyRNYI2m7+e5hbnDGnR1l34+faDQDNBunUML2isqa5lkISKF4hC9F4EYb+KNQA62vsDaWlB3m6R0E/2Kxv74U4YZIy8SrYxhI2N3brKKKIHQb2HbBlJhuV9TKR2BZ46C76+ejExTcGEzcmFT7cP0oibXoXm2iTRSFRJWlMtJCHnSbQ9y1jIOGCuJgGqFcI0LuFJnODzg9S/RXU6/VGmUukAYa30Q4C6uMhvjue9/+oEiwgEJ9V3cpOtn+MTwmfmHPGaX3bl5ZdyUwAh7DWStBGzgKR03oXNbgfaiq+Qq9m9f68X0qe3GwPVI6UCqdUs6luxpJK8T/6laQz4pXza20zKQV31rBbZHQIWF/pmVDKoWg4g2fbP3Ily0GVi7E+MsCMI=
  - secure: eaQAM49YeZ/NBgCn+xrDjoZyjja8/pYiGT03TWiEOiZ2lamXnswUmMGcP7DgJwl35LEEKEACa6r9iOFpPJvt/xbDLtsCjQJxBWYVbe1+hZfpJf0aXiP7qZaUfXk0xMng9TEdD97ZzDENzCwUPqiAhRFRc9jJ6ov2c9eYLi8FI/8Iv+5rbE4AvoY0EishG458RjmHTrk+NoKyRdO8RYNSwVJBf5issnbHg87FaKQbFUgobuX2ROyFTisgpGRQchsSUSA6YQPEIUe6ajdWAnXsDHRq7pCS8HIFmOmWuVEs0d3i6gbCMMRsPiA1X03EmBvvX0vdSYriwRHvugHdJmj6kOWpGknkky1lNV5TKv6yzERgi/gixs2p3E5Z49eu3r53T1B2jPXf/ksae/olnjLDl/kKlWdvgKklijcb7FgtsOJQjU9XyplsIzqJff/DdU1+nj18n4Ka3AE5JGNXZ3IZtyWOcQfJFOe9pDU+5cU4x75JxisLZev+OcFTuPmbEkSF3syzhH9cdqpef16+zx8IRASU4Nwer79JABlXi+SGjv22ea1LHEzr5WZLMReQmmRZfgBh0zFGGn+aZ/jkA4NBqu6rIUR/ywHlPnn6tXUGlCwh/kn6BndESoXyfxAAWRN6yV/m1g60/Ah7eVb6ZaT8MX/I4gWvpZXeOQFDCSzMeHM=
  - CONSOLE_GITHUB_CLIENT_ID=d9d4887f478eb4c7beb1
  - CONSOLE_BASE_URL=http://localhost:3000
