sudo: required
dist: trusty
language: node_js
node_js:
- 8
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_script:
- npm run build
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJ4OOWY6UUWDWKGZA
  - AWS_S3_BUCKET=resourcesco-console-data
  - GITHUB_CLIENT_ID=d9d4887f478eb4c7beb1
  - BASE_URL=http://localhost:4567
  - GITHUB_USERS="benatkin:4126,resources-test:37493865"
  - TEST1_GITHUB_USERNAME=resources-test
  - TEST2_GITHUB_USERNAME=resources-test2
  - secure: gUm2gV2tVPJw2+7qhgFPFIUdTMGb3/rgsyFE4OA4kRsNyvrUQSPSOj+ul986/0x2dvNgeREE5mBPhdzWMrvc3phOOlhLiUUOB2Ouqa35N7e+JFvmbdLZ041rpQAiMFbe4bD+eHaLT45e0H4WIbiN1HZOLx/Obf3H5pdhdyFIxrGfkVXvEyLgPX2+LBjT3p3sx8Hp5vZsRaCk+z+sPFKrrvbbSVkTDXHCVBSkMv+z4d66K3ZU2pTCxKJ6em78843hcJxaVEqDnXjWyZEFGEvB56bP28MUlm5iSGa5TY0EuoysktkuYX+yIlaWi3HnIEGYcxtBeCLh8hSO9FEJbfDGBcHpn9U3tKvLpcmBAVSIYrqcupTyCfOS6XUFwh0XSLLkZwdUoSjVORIvbVGg89y7a8OxRTtlw/Ej1nShH2a3fIv843mqQWjClFsE75ixxXF/pZIfvFuwDn9MIEt4GmctzMkl359VJzfJG3pjTJ29apUy3WDgrSSYHQsF6GCxzm4MZ9y9lm3qymOmgiwJGXlKGm9WffTvCZYFYnrgPSFeDo9GvlJPaR8E1RHmxtm0rlKViNCwIVQHiXzcel7N49rbs6oLDmudra7RlKc7TUwsMt5Z/iv3cIloqETD/+f7ZD+XIl5oID3ryJsamn4bLYPZhY+EsAWYAU0w2jUV+Yyo+k8=
  - secure: gckABZvO0HsrBAYCAbh2oaYKVDzh9PdcjpmO6rmpQ0EjyvQyOyOgUw6rancflU68Uph0A2WzCDc8+10ogv+ocVHB26m7n4N4soxIWWZQf76JLI38DEN7wBkbYZumYSi1XDHfVZzLSj3gB5fkaKVVBmgFtB7TU/KsGEQxf7HKMIu96VIy6PQcUrZQsaMf3UrVki7KKiHgzpF0g8ANO+j8o2+cXiJaLlGFUoWjoPyFNyivZXcYHFYbPr1W6btL8T9LRxOu5vYRtcSCtjVjX85P576KmM2z4i4JlZqnPpEWPErT1UUNNubHz1xs7iRwoSr8HLHar6F1gCsqOzIZyN+XrrWIVhWOCtGWNPJKYtM2VxGEdvF32seTlGZMEy/qV7VxZhUi+oPQSly9NDdKe8o3zFqo+JgDv5ZvlUngMHDQPLqN1xf6uiwR/QIhMJIxP1kU9Pdb84TGBIvFDH+uEfk9UaKHBoP4zGUka278+MOA9A41Aa8RRHSztra98Q04NKabPXMOyOMDpvyGz7b6B6+Tg0xJuREa7HpS/F390YNzddTpsqlRv1rjJG0837QOscS7JrDKMLVEiICVMCUaawihgBEfYWBhQQU2zGokV8TrTkpYZlb9ghspqL06rffoqJzBlQNixfwg9N5fLUS+5aDRFPVUo65vIpRHjsKjQ1TDyhg=
  - secure: g/zXn9jscjtrEVepRh39VZPKQ/lOhdDtw/L4rMKApufLvpDvpxhBYqlyap4xMwVbrwVdaLi1j8n5VkSeb3UfbzeVPvO2ZKtKS8wSOgmDukM2E+Ss3RhUnvrPQ+2oLYPNM7MN+pwb3I/fhzG+LZL63dM3azVJGD4OXMtjyPpXxYmBkTw5kuO1aK19SdEef4DRPHln2kc8i2NJksUhghInFfUx1pFY6QhjYmmhjVGmgpeJn0+s33CUQcmq6AB0LWMHKZ7K9i5nOtevSWZTPUG5OQwyaGaxdXXim3YwcTgUk4hlF/W1ukoIVBh+14bFxUcO7Oez0gQqd5MrqK/p/XSohG8yjZB7H4hD9x0a4F0wj6r8ByGTHI8W7nYKf0qeQo9FLCPxUeLP14th+CWmI0ULcwc4EuRZ7nGdKGcgS+2RHgzDkG2w1usIebw6wGAxbBpxxqy7moOht5SFUGTZgHnX7NAcY4dDtrdVpjCvN7GQd5uzllvzquFTOi+68HDET4aPmW0b20BSXR3bZbsIV5iL+cSCNidfaBb5WAf2XcfDTeg5jgBaDj5ocaHHajLzGuxUbxAoB9fqxNAahQGa5NoXCpnjlMGVUY1waym4FRCTvjORNKdmO1mMOHLB59NzwxMtu7HQ5gSYTiWK1OUJjHYv0RLclria/IOwK0QvuUi4W1A=
  - secure: cwvbXqFUPs5DB13iJhtt6MLjAPZ5yBCdSiFjHe3RxxZeOTGY6pFUN6FWovr0OGiAxOCdHcLVB9vfxWs/0zBjTNqwXSHeTEHXmpWMao9L9U1Kvvy0Ov6Nxiq1L67R1Sz62iqFU75q2YYdOmiT0pXQSaKlAcDRlL/neErWnrEDKzURtXNFnwHAhjnSIJ8nPoBn5knittkbsrB1/6cTyhDmLE15q1ZzWSSzaxhonLISN5zwpwdg7a1q6cX4WnyIkWrqqfXJypt6Xzq0TyeVmgx6NSA5dIxqO6OaHQ5H9xfs+N/bQgSMkjMUXQ0hq5U/rG09t54P12f+qEg3JsqSYEIF3TM1OG7q1J2ChgC3YruWRho82kxf14VuzppF1Ad26vhBT4qPlpM/9fbqRUyexkl8mNwgueeYrbm8KGl0lUlDyKOwR7jgFuLSAp2O0O6g0hgUf5V4rDsNfPRvKnM44y943bBNop/wfP3fHoBJRfhF3bvMhYUk5hoVRkUqVRmn+ZiLmxR2i0/7SkNfrKtN2LH9vt3N+qvBR7YtaZwvpgvqRkpNQKw8Tr7SajsKBcn3tQ0oeCfTnsQ+OOhMa27crJvQuCMUFo2KEGjngvDhWAyUhg7eg8Ygn20elgD3GXcpx7dgD8X0hF7dsT5A/itnOLvyGUUvqow9As476KW55Sym0QM=
  - secure: hMiIRuK+cRXAW3Y2vad9meHrJfSYBg45VtLgDe48yIBRdUf01pe0/gxjMGsDr5Kxvb/zubT6iNph3rICTrVOzV6Kku2HoX2UctF9z97NLHxA4GatmX8Y62X38QTAVBiVPN5dRFc7MzeMSpC2a0lEidDmcAudg27pXir1pRLZCvPZtczPVR3TI17Hkahd/DShAIXrRWek7SZoRNer7QZ28yAnOcoNjczLec6wNAWEx3aQgesKlBAaoD0LwHb9V9xUhVp3rkCmWhjtPIhhKokRh8gB2oG9dpiLZ+lL9MWLJ9rUXXlpyzplVwaUe9T7zp1pjbsv1rTTN+SWttPYkcwDD+7wbGdooKAUUexQfGZtNyW78oTt4oyF5LKK+18f3oniSr5lKQ+/iWqxKKEAYtmK23LVfj4If8mqEwK9WfYM/1HWJGUb95lIwwnX8/pe+kePqL8CQgIOQWt5//+wTM0f50IfXdZAkHeii61+KW89TC8TYSq+0LuWGYTZ3UhbP1a6KPs8zlqVOsssxnrRuqoVzyeRM3avIxxkokqgLK5pDw85JXDI66Omrq6WKHrqAaIrI1X9rk5GHzsRUGCmsF/CBHvi8qZmM3Hvz3u7fHvUNis4NAhq17m71BlZDa2Ad1w/oQWN8eX9lFoP0O159SvrPLJu1SL7jV1pBFcN4pLkGiI=
