sudo: required
dist: trusty
language: node_js
node_js:
- 8
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_script:
- npm run build
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJ4OOWY6UUWDWKGZA
  - AWS_S3_BUCKET=resourcesco-console-data
  - GITHUB_CLIENT_ID=d9d4887f478eb4c7beb1
  - BASE_URL=http://localhost:4567
  - secure: Tl/g8izzmha/8H1NVEY8LWc+DvVchK7RVW4gCcW1JDHSAlERXhia0fpxN8sjo1/r+HJ7QBgFIVAYXVlCMj5l69LtVHS8MwflxbV0hPXdXVoc6GDco6Xjc1xF9Y4QK/FKJYdzo6L/BZ2/d9hKvIEK2I4dLs5RvLjqMK/YvQe0N/c4C+Yi/XFrj1nfz/0tyi/EyYR+Vkww2eAyvpvos0Xhn9AVEYRNJ/mrvvclI0qvKBKfnZb3w8F5oGbqDUILomt7wWMiTJey4kU2t8gp3+i8KS0ap7u7B+zKAQN4XAe0vgMEJL1ftQeJR145yHQa9rSNaE8wIyRMC/QHRkztfru1bwSQJn5xBSHowrZ2uBOppEvJ40zfMoFAWZ1jXwNfwmbx/OVjTTCTF812S1qw0p0S+bHmRofW2q2MK884DIybwvruqeKyFThJpSOSWMFmUjhllQQ+1pJOsGqDP7ryW9687ws8QUWu4CXIhVD6ohY7JC7V0RIUOk4QaVQIWGE4n5CUKKIcmGU6sWeatke4nH4heCVnbOQcbrZVxxY7GbkGxLuIyQESkfE1WQP8xp9ljUCh2xJxbSg+NNPXL5N8g+l57HW0Ld4YPLlo/rKjQUQhv3MiIM2KGH5QrGU7ATeR0PyC+XsVuLdEULi3I2o4tdqw8j+01Fy5+Zpu87C7JkAOKEQ=
  - secure: TJYGL9P9hR7QlRskf0hmmBceosq2lAEY2H1dO6FsGiWL3Gb2M/TsBqwuxr2IBQs3S83pUEAIKh8z3yk753YJXWgv5feMveiZn2iAZkMBXaQIqhWfGBoN0RImnf/u2TIDB7ImrJrq3/LCaAf3Qj8n4GMo5pNaWE4R9wsdqzb1XSV8+mgSGWrJcNarbfyOdSwkd01Vpwt8rIGWCz+hfXsLVuu6HBzjTpe3iYmwMs1DCtBu2PIjpslgfwqz7ssaot3/q9T4Ichg8+yhse1+pUXbNdoc0qeUMKgC9eY/tTdXZcwNi+MM1qraGMCuK6iGLqXfDqQPE8/b6HaNduvPlomiQduM7KxJQKNAYjqNtBGV4TFPSsVa7pPAz1uvU+Wayt1iPxEioocfNGIQNAS26RvESzUjUjgQRk4aVig8klZNibx7MjQEmHdbO5J0PqqQ3EJITjjRpsgT1qCi6XN2KnJwxRVwOn8GsJnsNOw/F2dtrLVn8t0Iw2KCIsgEWJ2/4JD2PSAMgbPY2/5sfeSVHIdyBrM/a7QMybrx/sQJETYkPInuvz1wILilWpcQ6fRRdpYZEmb4Q4SamJUPB7itZWvweTHeVLSS6SqIo2BdHFyjgdLU6LKSLs/uqLZHRf6LpvXvYYWGi3pucZrzTivysQyZlVMhtLLB3hTCi5Bb4q1wXzg=
  - secure: bXN5P6YXPtnyZY/qEaTc1pqkYgaJL7PIbCrwI4gvvjL4knhsOxSXkg7td5853b1lz7AV02IBqgvmMnXjV+73+ZRHnPjqaYsJ9cjvOMEUk7FpIQ07+OLL4g5d4dxD3+cSsMMSIw93Oi5FRoKYxxYhbmKDhYMSG1A9YSqsr51Xu4xHmmSm7Q5QV9C704w0XKDJbote4ihaIxjVvEq2IOGBNidSaiTHEkHSa2Dbu/igbCyQhBlf9XKJO3xWPnpZtedRZXQDTRq+SyGQ7ur9hsDqeS34tIhbMNqwJB4Y1WRkpEQyckLKeUZPFG9IsmU4m1PwEA6hgvYrB2obtXblRrOCyULqRP8lUBud80WbqbQTLXxfdp2KbWUVoJ5wuiOVrGYiyri8Ru/St8bY5gS0hjFv0poNgQCQ419onC08wFOmnV4wjpcQ5PeDPT0U1o4+cARS0mAfG11M0INf0dttnfbqJBRqG8z7CyVBIIcMZAeaYZ1Ho3/aGqM4Cla30Ihu70072STJSKaUS8hIXW90TPSEYbDXsWrQ3yoIf6bWYvqtxO2V6cIKCwd9q1/ZcampTtVw/mKg5TxkGcdf9YJGakKVw8ONwe8Ag0ifrCSqj2/z0T/X5AY+cnLxMTtOLvULbrY2/9b8opQ034TaM1hFfkbmW4RUZH4FJrsshwkzKT6U4rc=
